# Allow configuration in yaml files to be overridden by environment variable values
youTubeApiKey: KILLRVIDEO_YOUTUBE_API_KEY

cassandra:
  keyspace: KILLRVIDEO_CASSANDRA_KEYSPACE
  replication: KILLRVIDEO_CASSANDRA_REPLICATION
  dseUsername: KILLRVIDEO_DSE_USERNAME
  dsePassword: KILLRVIDEO_DSE_PASSWORD

loggingLevel: KILLRVIDEO_LOGGING_LEVEL