# Default schedules for running tasks, parsed by Later.js text parser
# (see http://bunkat.github.io/later/parsers.html#text for examples)
schedules:
  addSampleComment:
  - every 1 minute

  addSampleRating:
  - every 20 seconds

  addSampleUser:
  - every 30 minutes

  addSampleVideo: 
  - every 30 seconds

  addSampleVideoView:
  - every 1 seconds